
OBJS-$(CONFIG_V4L2_M2M_M2M_EXP)                += v4l2_m2m_exp/v4l2_m2m.o v4l2_m2m_exp/v4l2_context.o v4l2_m2m_exp/v4l2_buffers.o v4l2_m2m_exp/v4l2_fmt.o


SKIPHEADERS-$(CONFIG_V4L2_M2M_M2M_EXP)         += v4l2_m2m_exp/v4l2_buffers.h v4l2_m2m_exp/v4l2_context.h v4l2_m2m_exp/v4l2_m2m.h
